name: Terragrunt AWS Execute
description: "Authenticates to AWS then invokes terragrunt"
inputs:
  gruntwork_code_access_token:
    description: "The GRUNTWORK_CODE_ACCESS_TOKEN secret"
    required: true
  working_directory:
    description: ""
    required: true
  account_id:
    description: ""
    required: true
  account_role_name:
    description: ""
    required: true
  role_session_name:
    description: ""
    required: true
  chain_account_id:
    description: ""
    required: false
  chain_account_role_name:
    description: ""
    required: false
  gruntwork_context:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: "[Baseline]: Read account request"
      id: gruntwork_context
      uses: gruntwork-io-team/pipelines-bootstrap@main
      with:
        cache: ${{ inputs.gruntwork_context }}

    - name: Authenticate to AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ steps.gruntwork_context.outputs.default_aws_region }}
        role-to-assume: "arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.account_role_name }}"
        role-duration-seconds: 3600
        role-session-name: ${{ inputs.role_session_name }}

    # If we're doing a pipelines policy update, assume the role in the child account from the mgmt account
    - name: "[Terragrunt Execute] Authenticate to Chained AWS account"
      if: ${{ inputs.chain_account_id != '' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ steps.gruntwork_context.outputs.default_aws_region }}
        role-to-assume: "arn:aws:iam::${{ inputs.chain_account_id }}:role/${{ inputs.chain_acct_role_name }}"
        role-duration-seconds: 3600
        role-session-name: ${{ inputs.role_session_name }}
        role-chaining: true

    - name: "[Terragrunt Execute] Confirm Account Access"
      shell: bash
      env:
        ACCOUNT: ${{ inputs.account_id }}
        WORKING_DIRECTORY: ${{ inputs.working_directory }}
      run: echo "::notice ::Running in account $ACCOUNT and planning in $WORKING_DIRECTORY"

    - name: "[Terragrunt Execute] Run terragrunt ${{ inputs.terragrunt_command }} in ${{ inputs.working_directory }}"
      id: terragrunt
      uses: gruntwork-io/pipelines-execute@v3.0.0-beta4
      with:
        token: ${{ inputs.gruntwork_code_access_token }}
        tf_binary: ${{ steps.gruntwork_context.outputs.tf_binary }}
        working_directory: ${{ inputs.working_directory }}
        pipelines_cli_version: ${{ steps.gruntwork_context.outputs.pipelines_cli_version }}
        terragrunt_command: ${{ steps.gruntwork_context.outputs.terragrunt_command }}
        infra_live_repo_branch: ${{ steps.gruntwork_context.outputs.branch }}
        gruntwork_config_file: "${{ steps.gruntwork_context.outputs.gruntwork_config_file }}"
        infra_live_repo: "."
        infra_live_directory: "."
        deploy_branch_name: ${{ steps.gruntwork_context.outputs.deploy_branch_name }}
